// IDEA Event Registration Tracker -- data file
// GENERATED by scripts/update_data.py -- do not edit by hand.
// To add an event, add an entry to events.config.json instead.
// Timestamps only -- no names or emails on this public page.
window.IDEA_EVENTS = [
  {
    id: "mookherjee-seminar-2026-08",
    name: "IDEA Research Seminar - Dilip Mookherjee",
    eventDate: "2026-08-05",
    note: "Aug 5, 2026 \u00b7 9:00 AM US Eastern",
    timestamps: [
      "2026-07-23T13:52","2026-07-23T13:52","2026-07-23T13:52","2026-07-23T13:52","2026-07-23T13:52","2026-07-23T13:52","2026-07-23T13:52","2026-07-23T13:52"
    ]
  }
];
