#!/usr/bin/env python3
"""Regenerate data.js from the Google Sheets listed in events.config.json.

Privacy: only the registration-timestamp column is read and written.
Names and emails never leave this script.

Per-event timestamp caches live in data/{id}.json. If a sheet fetch fails,
the cached copy is used, so a transient outage never blanks the page.
"""

import csv
import io
import json
import sys
from datetime import datetime
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "events.config.json"
CACHE_DIR = ROOT / "data"
OUT = ROOT / "data.js"

TS_FORMATS = [
    "%m/%d/%y %H:%M",
    "%m/%d/%y %H:%M:%S",
    "%m/%d/%Y %H:%M",
    "%m/%d/%Y %H:%M:%S",
    "%Y-%m-%dT%H:%M",
    "%Y-%m-%dT%H:%M:%S",
    "%Y-%m-%d %H:%M:%S",
    "%Y-%m-%d %H:%M",
]

HEADER = """\
// IDEA Event Registration Tracker -- data file
// GENERATED by scripts/update_data.py -- do not edit by hand.
// To add an event, add an entry to events.config.json instead.
// Timestamps only -- no names or emails on this public page.
"""


def parse_ts(raw):
    raw = raw.strip()
    for fmt in TS_FORMATS:
        try:
            return datetime.strptime(raw, fmt)
        except ValueError:
            continue
    return None


def fetch_timestamps(url, column):
    resp = requests.get(url, timeout=60)
    resp.raise_for_status()
    text = resp.content.decode("utf-8-sig")
    if text.lstrip()[:1] in ("<", "{"):
        raise RuntimeError(
            "Response is not CSV -- check that the sheet is shared "
            "'Anyone with the link: Viewer' (or published to the web)."
        )
    rows = list(csv.reader(io.StringIO(text)))
    if not rows:
        raise RuntimeError("Empty CSV.")
    header = [h.strip().lower() for h in rows[0]]
    try:
        idx = header.index(column.strip().lower())
    except ValueError:
        raise RuntimeError(
            f"Column '{column}' not found. Header row: {rows[0]}"
        )
    out = []
    for row in rows[1:]:
        if idx < len(row):
            ts = parse_ts(row[idx])
            if ts:
                out.append(ts.strftime("%Y-%m-%dT%H:%M"))
    if not out:
        raise RuntimeError("No parseable timestamps found.")
    return sorted(out)


def js_event(ev, timestamps):
    lines = []
    for i in range(0, len(timestamps), 8):
        chunk = ",".join(f'"{t}"' for t in timestamps[i : i + 8])
        lines.append("      " + chunk)
    body = ",\n".join(lines)
    return (
        "  {\n"
        f'    id: {json.dumps(ev["id"])},\n'
        f'    name: {json.dumps(ev["name"])},\n'
        f'    eventDate: {json.dumps(ev.get("eventDate", ""))},\n'
        f'    note: {json.dumps(ev.get("note", ""))},\n'
        "    timestamps: [\n" + body + "\n    ]\n"
        "  }"
    )


def main():
    config = json.loads(CONFIG.read_text())
    CACHE_DIR.mkdir(exist_ok=True)
    blocks = []
    hard_fail = False

    for ev in config:
        cache = CACHE_DIR / f"{ev['id']}.json"
        try:
            ts = fetch_timestamps(ev["csv_url"], ev.get("timestamp_column", "Registration Time"))
            cache.write_text(json.dumps(ts))
            print(f"[ok]   {ev['id']}: {len(ts)} registrations")
        except Exception as exc:
            if cache.exists():
                ts = json.loads(cache.read_text())
                print(f"[warn] {ev['id']}: fetch failed ({exc}); "
                      f"using cached {len(ts)} registrations", file=sys.stderr)
            else:
                print(f"[fail] {ev['id']}: fetch failed and no cache: {exc}", file=sys.stderr)
                hard_fail = True
                continue
        blocks.append(js_event(ev, ts))

    OUT.write_text(HEADER + "window.IDEA_EVENTS = [\n" + ",\n".join(blocks) + "\n];\n")
    print(f"Wrote {OUT.relative_to(ROOT)} with {len(blocks)} event(s).")
    if hard_fail:
        sys.exit(1)


if __name__ == "__main__":
    main()
